# 推論統計 (Inference Statistics) {#ch-infer-stat}

推論統計欲由資料來推論母群分配的特性，通常是母群的參數。一般而言推論統計可以分為兩種取向：**估計 (estimation)** 參數或**假設檢定 (hypothesis testing)**，當中，估計又可分為點估計（point estimation）與區間估計(interval estimation)，而區間估計通常採用信賴區間（confidence interval）。總而言之，推論統計通常有以下三種方法：

1.  **點估計（point estimation）：**如何建構估計式 以估計參數 。
2.  **信賴區間（confidence interval）：**以信賴區間 $[LL, UL]$ 作為 的區間估計，能保證該區間的信心水準（confidence level）。
3.  **假設檢定（hypothesis testing）：**建立對於 的虛無假設 $H_0$（與對立假設 $H_1$），並根據資料決定是否能夠拒絕虛無假設。

## 學習目標 {#sec-infer-stat-goal}

-   基本概念：統計量與抽樣分配

-   推論統計介紹：點估計、假設檢定、信賴區間（一種區間估計）

    -   方法一：點估計

        -   樣本平均數的特性：中央極限定理

        -   樣本變異數的特性

    -   方法二：假設檢定

        -   單一樣本平均數的假設檢定：Z、t檢定

    -   方法三：信賴區間

        -   單一樣本平均數的信賴區間：Z、t區間

## 

::: {#def-finite-infinite-popu}
## 有限/無限母群 finite/infinite population

1.  如果母群數有限，則此母群為**有限母群（finite population）**。
2.  如果母群數無限，則此母群為**無限母群（infinite population）**。
:::

註解5.1. 在心理學當中，儘管研究者關心的母群常為有限母群，但由於有限母群的統計特性較為複雜，故通常假設為無限母群之情況。有限母群的情況只會探討不同抽樣方法的特性與結果。  

定義6. \*\*\*（無限母群模型） (i) 若 相互獨立，且分配都來自於F，則稱 為「來自母群F(x)之隨機樣本（random sample）」或「來自F(x)之獨立同分配（independent identically distributed, i.i.d.）」。數學上記作 。 (ii) 為一單變量資料集，其中n為樣本數、 為第i個觀察值。 (iii) 參數（parameter）可以決定母群分配F。參數通常以 或其他羅馬字母表示。

定義7. \*\*\*（統計量） (i) T為一個函數， 為統計量（statistic）。亦即，統計量為資料的函數（計算的結果）。 (ii) Y為統計量，Y的分配被稱作Y的抽樣分配（sampling distribution）， (iii) 抽樣分配的標準差被稱作標準誤（standard error）

模擬8.\*\*\* (繪製抽樣分配) 為統計量（statistic），若要繪製Y的分配，則可以依照如下步驟： Step1. 隨機從母群當中取後放回（with replacement）抽取n個樣本點，計算出Y。 Step2. 重複上述流程，並將每一次得到的Y會製成直方圖，若抽取次數k趨近於無限大，則繪製出來的直方圖會趨近於Y的分配。

註解8.1. 儘管在數學定義上，統計量Y的抽樣分配為「Y的分配」。但是在心統與教統上為了要解釋分配是什麼，會以模擬8的方法來作為「Y的分配」的定義。在回答名詞解釋的題目的時候，只要遇到統計量的分配，都可以用此方式說明分配的概念。在本課程當中此後並不多對分配多作如此解釋。

## 樣本平均數的推論統計（單一樣本） {#sec-sing-samp}

## 推論統計方法一：點估計

## 推論統計方法二：區間估計

## 推論統計方法三：假設檢定
